### ISSUE TITLE
Using variables possible?

### ISSUE THREAD

**Issue by nevace** [postcss/postcss-media-minmax#13]
Hello,

Would it be possible to add support for variables in place of the value. As far as I'm aware it doesn't work but I'm not sure it would even be possible either. I think plugin order would be an issue.

Thanks,

**Comment by MoOx** [comment]
You should add https://github.com/postcss/postcss-custom-media before this plugin.

**Comment by nevace** [comment]
I have this but was trying something like this..

$tablet: 540px

@custom-media --tablet-above (width >= $tablet);


I have the precss set of plugins.

**Comment by MoOx** [comment]
precss probably doesn't handle `@custom-media`. You should open an issue over there.

**Comment by nevace** [comment]
Ok thanks.
