### ISSUE TITLE
media queries in @import?

### ISSUE THREAD

**Issue by hgl** [postcss/postcss-media-minmax#17]
It would be great if 

``` css
@import "foo.css" (width: >= 300px);
```

Could be compiled to 

``` css
@import "foo.css" (min-width: 300px);
```

When postcss-import is not used.

Quick question, does postcss-import support inlining the following?

``` css
@import "foo.css" (width: >= 300px);
```

Does it relate to this plugin?

**Comment by woble** [comment]
Looking at the code it doesn't support it.

`postcss-import` does not support this type of importing either.

**Comment by MoOx** [comment]
postcss-import just wrap content with the media query so if you use it before this plugin, it should work.
Otherwise, PR welcome.

Just a side note: `(width: >= 300px)` is invalid. It's `(width >= 300px)`.
