### ISSUE TITLE
VC Code + Svelte/Sapper trouble

### ISSUE THREAD

**Issue by koddr** [postcss/postcss-media-minmax#25]
Hi! 👋  Many thanks for this PostCSS plugin.

I have some trouble with it at my VS Code:

```console
Version: 1.46.0
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T08:59:06.977Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0
```

I use latest [Sapper](https://sapper.svelte.dev/) version:

```json
    // ...
    "sapper": "^0.27.15",
    "svelte": "^3.23.2"
}
```

And its linter always show me this error:

![Screenshot 2020-06-12 at 13 32 35](https://user-images.githubusercontent.com/11155743/84502071-58b24d80-acc0-11ea-90d1-4c64e0eaf3a4.png)

How to solve this? Maybe someone faced with similar problem?

Thanks! 😉

**Comment by Semigradsky** [comment]
@koddr try to disable diagnostic messages - https://github.com/sveltejs/language-tools/tree/master/packages/svelte-vscode#svelteplugincssdiagnostics

As I understand `svelte-vscode` doesn't support new css features.

**Comment by koddr** [comment]
@Semigradsky thanks for reply, but it's not (fully) works. 

VS Code CSS validation is gone, but I still see `css-syntax-error` message by Svelte:

![Screenshot 2020-06-13 at 13 04 54](https://user-images.githubusercontent.com/11155743/84566074-01bb7f80-ad77-11ea-914b-3d23d0a9d98b.png)

```console
Colon is expected. If you expect this syntax to work, here are some suggestions: 
If you use less/SCSS with `svelte-preprocessor`, did you add `lang="scss"`/`lang="less"` 
to you `style` tag? If you use SCSS, it may be necessary to add the path to your NODE 
runtime to the setting `svelte.language-server.runtime`, or use `sass` instead of `node-sass`.
Did you setup a `svelte.config.js`? See https://github.com/sveltejs/language-tools/tree/master/packages/svelte-vscode#using-with-preprocessors 
for more info.svelte(css-syntax-error)
```

There may be a way to tell Svelte parser to support your PostCSS plugin in `*.svelte` files?

**Comment by Semigradsky** [comment]
There is no need to support 'PostCSS plugin', need to support ['CSS Media Queries Level 4' feature](https://drafts.csswg.org/mediaqueries/#mq-range-context).

Feel free to open issue in the `sveltejs/language-tools` repo, that is not a `postcss-media-minmax` issue.

**Comment by koddr** [comment]
@Semigradsky thanks!
