### ISSUE TITLE
Support < and >

### ISSUE THREAD

**Issue by MoOx** [postcss/postcss-media-minmax#5]
Currently `(20em < width <= 50em)` is not transformed.
I understand it's a bit tricky to transform < and > when playing with (r)em because we cannot really do that for now.
But we know that .01em is a good 1px gap http://tzi.fr/css/responsive/prevent-double-breakpoint#tl-dr.
Maybe we should handle that.

**Comment by yisibl** [comment]
`(50em >= width > 20em)` Does this case to be also supported?

**Comment by MoOx** [comment]
Indeed 

> For example, (height > 600px) (or (600px < height)) returns true if the viewport height is greater than 600px.

**Comment by yisibl** [comment]
http://dev.w3.org/csswg/mediaqueries/?c=M%3BO%3DD#mq-range-context

**Comment by MoOx** [comment]
Hey that where I get the quote :)

**Comment by yisibl** [comment]
What do you need me to transformed? I don't understand. Can you give an example?

**Comment by MoOx** [comment]
Currently by writing `(width <= 50em)`, this plugin transform that to `(max-width: 50rem)`.
But writing `(width < 50em)` doesn't transform the code. Because `<` and `>` (without `=`) are not supported. We should support that (so we need to handle a 1px gap, even for (r)em).
Is this more clear ?

**Comment by yisibl** [comment]
input:

```css
@media (width < 50em) {}
@media (width < 320px) {}
```

output:

```css
@media (max-width: 49.99em) {}
@media (max-width: 319px) {}
```
Right?

**Comment by MoOx** [comment]
looks good.

**Comment by MoOx** [comment]
Maybe @tabatkins can confirm it should be good enough for a start :)

**Comment by yisibl** [comment]
input:

```css
@media (width > 50em) {}
@media (width > 320px) {}
```

output:

```css
@media (min-width: 50em) {}
@media (min-width: 320px) {}
```
Right?

**Comment by MoOx** [comment]
Don't think so. I would say both `<` and `>` implie a 1px gap. Only exact value when `=` is involved (so for `<=` and `>=`).

So I think

input:

```css
@media (width > 50em) {}
@media (width > 320px) {}
```

output:

```css
@media (min-width: 50.01em) {}
@media (min-width: 321px) {}
```

**Comment by tabatkins** [comment]
Correct that `(min-width)` corresponds to `>=`.  However, your examples that slightly bump the value are wrong.  Unfortunately, there's no way to do it correctly without boolean algebra, which is *also* introduced in MQ level 4, so it's unlikely that you'll have the right tools to emulate `>` without also having `>`.

(The right way is to rewrite `(width > 50em)` as `not (max-width: 50em)`.  The confusion that would undoubtedly result from actually writing that terrible MQ is part of why I finally got the WG to accept `>`/etc.)

**Comment by MoOx** [comment]
I understand what you explain but are your sure that using a 1px approximation isn't better than anything?
We are clearly doing some approximate transformation, but a opposite with 1px gap seems better than nothing.
`not (max-width: 1px)` seems to be similar to `(min-width: 2px)`. No?

**Comment by tabatkins** [comment]
Yeah, it's similar, and likely close enough to correct that it's fine to do.  It's just not *totally* correct.

**Comment by MoOx** [comment]
Sure it's not :)
Thanks for your input @tabatkins!

So @yisibl I think we can go with this

I
```css
@media (width < 50em) {}
@media (width > 50em) {}
@media (width < 320px) {}
@media (width > 320px) {}
```

O
```css
@media (max-width: 49.99em) {}
@media (min-width: 50.01em) {}
@media (max-width: 319px) {}
@media (min-width: 321px) {}
```

We should also offer an option to customize the gap

```js
postcss().use(minmax({
  gap: {
    px: 1,
    em: .01
    rem: .01
  }
})
```

Don't you think?

**Comment by ai** [comment]
I think too that we should support `<` even by this hack.

**Comment by outpunk** [comment]
+1
