### ISSUE TITLE
Use PostCSS 4.1 API

### ISSUE THREAD

**Issue by TrySound** [postcss/postcss-media-minmax#6]
PostCSS Plugin Guidelines are mandatory right now. Because all of rules are about ecosystem health.

**Comment by yisibl** [comment]
Done! Thanks to @ai https://github.com/postcss/postcss-media-minmax/pull/7

**Comment by ai** [comment]
Nice :) I am waiting a release :)

**Comment by ai** [comment]
@yisibl mice :) wait for release :)
